#! /bin/sh

# This minimal setup sets up bash and git
# Requires curl
# Bash (as opposed to Zsh) is used because of ubiquity
# Git is bootstrapped because it needs to be configured BEFORE yadm

REPO="https://dots.ree.to"

# Setup bash
curl -L "$REPO/.bashrc" --output "$HOME/.bashrc"
curl -L  "$REPO/.bash_profile" --output "$HOME/.bash_profile"
curl -L "$REPO/.zshenv" --output "$HOME/.zshenv"

SHELL_DIR="$HOME/.shell"
mkdir -p "$SHELL_DIR"
curl -L "$REPO/.shell/aliases" --output "$SHELL_DIR/aliases"

# Setup git
GIT_DIR="$HOME/.config/git"
mkdir -p "$GIT_DIR"
curl -L "$REPO/.config/git/config" --output "$GIT_DIR/config"
