[[ -f ~/.config/X11/Xresources ]] && xrdb -merge -I$HOME ~/.config/X11/Xresources
autorandr --change

# Caps Lock -> Ctrl/Escape
setxkbmap -option "ctrl:nocaps"
xcape -e "Control_L=Escape"

bash -c "cd ~/.config/i3 && make"
exec i3
