[[ -f $XDG_CONFIG_HOME/X11/Xresources ]] && xrdb -merge -I$HOME $XDG_CONFIG_HOME/X11/Xresources
autorandr --change

# Caps Lock -> Ctrl/Escape
setxkbmap -option "ctrl:nocaps"
xcape -e "Control_L=Escape"

# Automatic locking
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- $XDG_CONFIG_HOME/yadm/screenlock/lock &

make -C $XDG_CONFIG_HOME/i3
exec i3
