#! /bin/bash

# Use specified display or auto-configure based on primary
main="${1:-$(xrandr | grep primary | awk '{print $1}')}"

# Get connected screens
readarray -t connected <<< "$(xrandr | grep ' connected' | awk '{print $1}')"

cmd="xrandr "
found=false
for device in "${connected[@]}"; do
    cmd+="--output $device "
    if [ "$device" = "$main" ]; then
        found=true
        cmd+="--auto"
    else
        cmd+="--off "
    fi
done

# Make sure atleast 1 display is configured
if [[ $found = false ]]; then
    echo "$main is invalid or not connected"
    exit 1
else
    $cmd
fi

# Get random colour from Xresources
color=$(xgetres color$((1 + RANDOM % 6)))
color=${color:-#f1f1f0}

# In-place replace border-color
sed -i -e "s/\\(border-color = \\).*/\\1\"$color\"/" /etc/lightdm/lightdm-mini-greeter.conf
