#! /bin/bash

main="${1:-eDP1}"
res="${2:-1920x1080}"
rotate="${3:-normal}"

readarray -t connected <<< "$(xrandr | grep " connected" | awk '{print $1}')"

cmd="xrandr "
member=false
for device in "${connected[@]}"; do
    cmd+="--output $device "
    if [ "$device" = "$main" ]; then
        member=true
        cmd+="--primary --mode $res --pos 0x0 --rotate $rotate "
    else
        cmd+="--off "
    fi
done

if [ "$member" = false ]; then
    echo "$main is invalid or not connected"
    exit 1
else
    $cmd
fi

