#!/bin/bash
case "$1" in
    wallpaper)
        DISPLAY_SIZE="$(xrandr | grep \* | head -n 1 | cut -d' ' -f4)"
        TMPBG=/tmp/screen.png
        convert -scale "$DISPLAY_SIZE" "$(cat "$HOME/.config/wallpaper")" "$TMPBG"
        i3lock -i "$TMPBG"
        ;;
    *)
        TMPBG=/tmp/screen.png
        maim -u $TMPBG && convert $TMPBG -scale 20% -scale 500% $TMPBG

        i3lock -i $TMPBG

        rm $TMPBG
        ;;
esac
