#!/bin/bash
script="$HOME/.local/bin/wallpaper"
case "$1" in
    wallpaper)
        shift
        $script export
        wallpaper="$(cat "$HOME/.config/wallpaper")"
        i3lock -i "$wallpaper"
        $script set "$wallpaper" &
        ;;
    *)
        TMPBG=/tmp/screen.png
        maim -u $TMPBG && convert $TMPBG -scale 20% -scale 500% $TMPBG

        i3lock -i $TMPBG

        rm $TMPBG
        ;;
esac
