#! /bin/bash

case $1 in
    connect|c)
        shift
        nohup bash -c "ssh \"$1\" -X \"pgrep x2x 2>&1 >/dev/null && exit 1 || x2x -north -to :0.0\" || (echo \"Already connected to remote\" && exit 1)" >/dev/null 2>&1 &
        ;;
    disconnect|kill|dc|k)
        shift
        ssh "$1" killall x2x
        ;;
    help|h)
        echo "usage: remote [connect | disconnect] HOST"
        echo
        echo "commands:"
        echo "  NONE        - Toggle connection to HOST"
        echo "  connect     - Connect to HOST"
        echo "  disconnect  - Kill x2x on HOST"
        echo "  help        - Print this message"
        ;;
    *)
        nohup bash -c "ssh \"$1\" -X \"pgrep x2x 2>&1 >/dev/null && killall x2x || x2x -north -to :0.0\"" >/dev/null 2>&1 &
        ;;
esac
