#! /bin/bash
SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )
MUTE=$( pacmd list-sinks | awk '/muted/ {print $2}' )

case $1 in
    up|down) ([[ "$MUTE" = "yes" ]] || [[ -z "$2" ]]) && exit ;;
esac

case $1 in
    up)
        if (( NOW + $2 <= 101 )); then
            pactl set-sink-volume "$SINK" "+$2%"
        else
            pactl set-sink-volume "$SINK" "101%"
        fi
        ;;
    down) pactl set-sink-volume "$SINK" "-$2%" ;;
    mute) pactl set-sink-mute "$SINK" toggle ;;
    *) echo "$SINK" "$NOW";;
esac
