#! /bin/bash

if systemctl --user is-active "remote@$1.service" >/dev/null; then
    systemctl --user stop "remote@$1.service"
    polybar-msg hook barrier 2
else
    systemctl --user start "remote@$1.service"
    polybar-msg hook barrier 1
fi
