#! /bin/bash

BASEDIR="$HOME/shared/pictures/screenshots/$(hostname)"
mkdir -p "$BASEDIR"
NAME="$BASEDIR/screenshot from $(date '+%Y-%m-%d %H:%M:%S').png"

case "$1" in
	clipboard-interactive) maim -us | xclip -sel clip -t image/png ;;
	clipboard) maim -u | xclip -sel clip -t image/png ;;
	interactive) mkdir -p "$BASEDIR"; maim -us "$NAME" ;;
	*) mkdir -p "$BASEDIR"; maim -u "$NAME" ;;
esac
