#! /bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u "$UID" -x polybar >/dev/null; do sleep 1; done

# Launch polybar on all monitors
for i in $(polybar -m | awk -F: '{print $1}'); do MONITOR=$i polybar top & done
