#! /bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u "$UID" -x polybar >/dev/null; do sleep 1; done

# Set device
POLYBAR_DIR="$HOME/.config/polybar"
export POLYBAR_SCRIPTS="$POLYBAR_DIR/scripts"
export POLYBAR_MODULES="$POLYBAR_DIR/modules"
export DEVICE="$("$POLYBAR_SCRIPTS/device")"

# Launch polybar on all monitors
for i in $(polybar -m | awk -F: '{print $1}'); do MONITOR=$i polybar top & done
