#! /bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u "$UID" -x polybar >/dev/null; do sleep 1; done

# Set device
POLYBAR_DIR="$HOME/.config/polybar"
export POLYBAR_SCRIPTS="$POLYBAR_DIR/scripts"
export POLYBAR_MODULES="$POLYBAR_DIR/modules"
export DEVICE="$("$POLYBAR_SCRIPTS/device")"
[ "$(hostname)" = "zeus" ] && export WIRED_DISCONNECTED_ICON=""

# Launch polybar on all monitors
declare -A monitors
for i in $(polybar -m | awk -F: '{print $1}'); do 
    monitors[$i]="MONITOR='$i' polybar top &" 
done

primary="$(xrandr | awk '/connected primary/ {print $1}')"

# Start on polybar on primary monitor first
echo "$primary"
eval "TRAY_POSITION=right TRAY_MARGIN=2 ${monitors[$primary]}"

# Start on other monitors
for i in "${!monitors[@]}"; do
    if [ "$i" = "$primary" ]; then
        continue
    fi
    eval "${monitors[$i]}"
done
