#! /bin/bash
export XSECURELOCK_SAVER="$(dirname "$(readlink -f "$0")")/xsecurelock_saver"
export XSECURELOCK_DISCARD_FIRST_KEYPRESS=0
export XSECURELOCK_DIM_ALPHA=0
export XSECURELOCK_AUTH_BACKGROUND_COLOR="$(xgetres lock.background)"
export XSECURELOCK_AUTH_FOREGROUND_COLOR="$(xgetres lock.foreground)"
export XSECURELOCK_AUTH_WARNING_COLOR="$(xgetres lock.color1)"
export XSECURELOCK_FONT="Ubuntu Mono-18"
export XSECURELOCK_WALLPAPER_SCRIPT="$HOME/.local/bin/wallpaper"
export XSECURELOCK_BLUR_SCALE=20

# Set XSECURELOCK_WALLPAPER appropriately
# 1 monitor => blurred screenshot
# _ monitors => static wallpaper
# TODO: Add multi-monitor support for blurred screenshot
NUM_MONITORS="$(xrandr | grep -c ' connected')"
if ! command -v maim >/dev/null && ! command -v convert >/dev/null; then
	NUM_MONITORS=-1 # Force static if maim or imagemagick unavailable
fi

case "$NUM_MONITORS" in
	1)
		XSECURELOCK_WALLPAPER=/tmp/screen.png
		maim -u | convert - -scale $((100 / XSECURELOCK_BLUR_SCALE))% -scale $((100 * XSECURELOCK_BLUR_SCALE))% -strip "$XSECURELOCK_WALLPAPER"
		;;
	*)
		XSECURELOCK_WALLPAPER="$(cat "$HOME/.config/wallpaper")"
		;;
esac
export XSECURELOCK_WALLPAPER

xsecurelock
