if command -v nvim >/dev/null; then
    export editor=nvim
    export EDITOR=nvim
else
    export editor=vi
    export EDITOR=vi
fi

export LESSHISTFILE=/dev/null

export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1

export XDG_CONFIG_HOME=$HOME/.config

# Nvidia
if [ -f /usr/lib/modprobe.d/nvidia-dkms.conf ]; then
    export __GL_SHADER_DISK_CACHE_PATH=$HOME/.cache/nvidia
fi

# Go setup
if command -v go >/dev/null; then
    export GOPATH="$HOME/.go"
    export GOBIN="$HOME/.go/bin"
    export path=($GOBIN $path)
fi

# Rust setup
if command -v rustc >/dev/null; then
    export CARGO_HOME="$HOME/.cache/cargo"
    export RUSTUP_HOME="$HOME/.cache/rustup"
    export RUST_SRC_PATH="$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
    export path=($CARGO_HOME/bin $path)
fi

# HTTPie setup
command -v http >/dev/null && export HTTPIE_CONFIG_DIR="$HOME/.config/httpie"

# Local executables
export path=(. $HOME/.local/bin $path)
typeset -U path
