if command -v nvim >/dev/null; then
    export editor=nvim
    export EDITOR=nvim
else
    export editor=vi
    export EDITOR=vi
fi

export LESSHISTFILE=/dev/null

export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1

export XDG_CONFIG_HOME=$HOME/.config

# Local executables
appendpath () {
    case ":$PATH:" in
        *:"$1":*)
            ;;
        *)
            export PATH="${PATH:+$PATH:}$1"
    esac
}

appendpath "$HOME/.local/bin"
appendpath .

# Nvidia
if [ -f /usr/lib/modprobe.d/nvidia-dkms.conf ]; then
    export __GL_SHADER_DISK_CACHE_PATH=$HOME/.cache/nvidia
fi

# Go setup
if command -v go >/dev/null; then
    export GOPATH="$HOME/.go"
    export GOBIN="$HOME/.go/bin"
    appendpath "$GOBIN"
fi

# Rust setup
if command -v rustc >/dev/null; then
    export CARGO_HOME="$HOME/.cache/cargo"
    export RUSTUP_HOME="$HOME/.cache/rustup"
    export RUST_SRC_PATH="$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
    appendpath "$CARGO_HOME/bin"
fi

# HTTPie setup
command -v http >/dev/null && export HTTPIE_CONFIG_DIR="$HOME/.config/httpie"

unset appendpath
