#!/usr/bin/zsh
export ANTIBODYPLUGINS="$HOME/.antibody/plugins"
export HISTFILE="$HOME/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

# Vim Keys
bindkey -v
KEYTIMEOUT=1

function zle-line-init zle-keymap-select {
    case ${KEYMAP} in
        (vicmd)     echo -ne '\e[1 q' ;;
        (*)         echo -ne '\e[5 q' ;;
    esac
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

# key bindings
bindkey '^[[A' up-line-or-history
bindkey '^[[B' down-line-or-history
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey "^[[H" beginning-of-line
bindkey "^[[1~" beginning-of-line
bindkey "^[[F" end-of-line
bindkey "^[[4~" end-of-line
bindkey '^[[3~' delete-char
bindkey '^A' kill-whole-line
bindkey '^X' sudo-command-line

# options
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt AUTO_LIST
setopt NO_NOMATCH
setopt AUTO_CD

# antibody
source "$HOME/.antibody/load.zsh"
antibody bundle < "$ANTIBODYPLUGINS"

# completions
autoload -U compinit && compinit -d

# git
alias g=git

# fzf
if command -v fzf >/dev/null; then
    export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd -I --type d'

    source /usr/share/fzf/completion.zsh
    source /usr/share/fzf/key-bindings.zsh
fi

# editor
alias edit='$EDITOR'
if command -v nvim >/dev/null; then
    alias nvimconfig="nvim ~/.config/nvim/config.vim ~/.config/nvim/plugins.vim"
    function nvimbench() {
        bench=$(mktemp) && /usr/bin/nvim --startuptime $bench $@ && tail -1 $bench && rm -f $bench
    }
fi

# package manager
if command -v pacman >/dev/null; then
    function pkgdiff() {
        flags="-Qqe"
        hostnames=()

        for var in "$@"
        do
            case $var in
                -*)
                    flags="$var"
                    ;;
                *)
                    hostnames+=$var
            esac
        done

        if [[ ${#hostnames[@]} -eq 1 ]]; then
            icdiff -U 0 -L "$(hostname)" -L "${hostnames[1]}"  <(pacman $flags) <(ssh "${hostnames[1]}" "pacman $flags")
        elif [[ ${#hostnames[@]} -eq 2 ]]; then
            icdiff -U 0 -L "${hostnames[1]}" -L "${hostnames[2]}"  <(ssh "${hostnames[1]}" "pacman $flags") <(ssh "${hostnames[2]}" "pacman $flags")
        else
            echo "usage: pkgdiff [flags] <hostname 1> [hostname 2]"
            return 1
        fi
    }
    alias remove-orphans='sudo pacman -Rns $(pacman -Qtdq)'
fi

# chrome
command -v google-chrome-stable >/dev/null && alias chrome="google-chrome-stable"

# file listing
command -v exa >/dev/null && alias ls="exa -xF" && alias als="ls" || alias ls="ls -xF" && alias als="exa"
alias la="ls -a"
alias lh="ls -d .*"
alias ll="als -lF"

# filesystem operations
alias mv="mv -v"
alias rm="rm -iv"
alias cp="cp -v"
alias df="df -hl"
alias du="du -h"

# python
if command -v bpython >/dev/null; then
    function python() {
        if [ "$#" -eq 0 ]; then
            bpython
        else
            /usr/bin/python $@
        fi
    }
fi

# SSH public key
alias pub="cat $HOME/.ssh/id_ecdsa.pub"

# clipboard
if command -v xclip >/dev/null; then
    alias c="perl -pe 'chomp if eof' | xclip -sel clip"
    function copy() { cat $1 | c }
    alias v="xclip -o -sel clip"
    alias cpub="pub | c | echo 'RSA public key copied.'"
fi

# IP
alias pubip="drill myip.opendns.com @resolver1.opendns.com | awk '!/;;/ && /IN/' | head -n 1 | awk '{ print \$NF  }'"
alias privip="hostname -i"

