#! /bin/bash
function service() {
    case "$1" in
	install)
	    # ownership transfer to prevent hijack
	    [ ! -f "/etc/systemd/system/$(basename "$2")" ] && sudo chown -R root:root "$2" && sudo -s ln -s "$2" /etc/systemd/system
	    sudo systemctl enable "$(basename "$2")"
	    ;;
	uninstall)
	    sudo systemctl disable "$2"
	    [ -f "/etc/systemd/system/$2" ] && sudo rm "/etc/systemd/system/$2"
	    ;;
    esac
}

function exists() {
    command -v "$1" >/dev/null 2>&1
}

function is_laptop() {
    [ ! -d /sys/class/power_supply ] && return 1;
    for filename in /sys/class/power_supply/*/type; do
        [ "$(cat "$filename")" = "Battery" ] && return 0
    done
    return 1
}

function msg() {
    echo -e "\n\t" "$@" "\n"
}

function root_install {
    sudo -s mkdir -p "$3"
    if [ ! -f "$3/$(basename "$2")" ]; then
	echo "$@"
	case "$1" in
	    cp) sudo -s cp "$2" "$3" ;;
	    ln)
		# ownership transfer to prevent hijack
		sudo chown -R root:root "$2"
		sudo -s ln -s "$2" "$3"
		;;
	esac
    fi
}

# trash-cli
exists trash-empty && systemctl --user enable --now trash-empty@2.timer

# neovim plugin manager
DEIN="$HOME/.local/share/dein"
if (exists nvim || exists vim) && [ ! -d "$DEIN" ]; then
    tmp="$(mktemp)"
    curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > "$tmp"
    sh "$tmp" "$DEIN"
    rm "$tmp"
    exists nvim && nvim "+qall"
    exists vim && vim "+qall"
fi

# pacman hooks
if exists pacman; then
    root_install ln "$HOME/.yadm/hooks" "/etc/pacman.d"
fi

# backlight
if is_laptop; then
    service install "$HOME/.yadm/backlight/backlight.service"
    root_install ln "$HOME/.yadm/backlight/backlight" "/usr/bin"
    root_install cp "$HOME/.yadm/backlight/90-powersave.rules" "/etc/udev/rules.d"
fi

# polybar vpn hook
exists polybar && exists nmcli && root_install cp "$HOME/.config/polybar/scripts/polybar-vpn" "/etc/NetworkManager/dispatcher.d"

# gui setup
if exists startx; then
    root_install cp "$HOME/.yadm/xorg/override.conf" "/etc/systemd/system/getty@tty1.service.d/"
    exists i3lock && exists i3 && service install "$HOME/.yadm/i3lock.service"
    exists xgetres && systemctl --user enable --now wallpaper@daily.timer
fi

# yadm
case "$(hostname)" in
    poseidon) yadm config local.class laptop ;;
    zeus) yadm config local.class desktop ;;
esac

if exists yadm; then
    # Ignore SSH config to allow gcloud changes to be ignored
    yadm update-index --assume-unchanged "$HOME/.ssh/config"
    yadm update-index --assume-unchanged "$HOME/README.md"
    [ -f "$HOME/README.md" ] && rm "$HOME/README.md"
    exists yadm && yadm alt
fi

