#! /bin/bash
# text="$(systemctl --user list-units | sed -n '/remote@/s/remote@\(.\+\)\.service.*/  \1/p')"
text="$(systemctl --user list-units | sed -n '/remote@/s/remote@.\+\.service.*//p')"
if [ -z "$text" ]; then
    echo "   $DEVICE   "
else
    echo "%{B$(xgetres polybar.color2)}   $text   %{B-}"
fi
