#! /bin/bash

laptop=false
for filename in /sys/class/power_supply/*/type; do
	if [ "$(cat "$filename")" = "Battery" ]; then
		laptop=true
		break
	fi
done

case $laptop in
	true) echo -n "" ;;
	*) echo -n "" ;;
esac

case $1 in
	long) echo -n "  $(hostname)" ;;
esac
